# -*- mode: yaml -*-

variables:
  - group: aws-credentials
jobs:
- job: docs
  pool:
    vmImage: ubuntu-16.04
  container:
      image: osgeo/proj-docs:latest
      options: --privileged
  timeoutInMinutes: 60
  steps:
  - script: |
      echo "current directory:" `pwd`
      cd doc
      make doxygen
    displayName: 'Make Doxygen'
  - script: |
      cd doc
      make html
    displayName: 'Make HTML'
  - script: |
      cd doc
      make latexpdf
      ninja
    displayName: 'Make PDF'
  - script: |
      export AWS_ACCESS_KEY_ID = variables['aws-credentials.AWS_ACCESS_KEY_ID']
      export AWS_SECRET_ACCESS_KEY = variables['aws-credentials.AWS_SECRET_ACCESS_KEY']
      cd doc/build
      aws s3 sync . "s3://pdal/docs/$BUILD_SOURCEVERSION/" --acl public-read
    displayName: 'Upload https://github.com/OSGeo/gdal/commit/$BUILD_SOURCEVERSION to https://pdal.s3.amazonaws.com/docs/$BUILD_SOURCEVERSION/html/'

